name: simbio-paper
channels:
  - conda-forge
  - alubbock
dependencies:
  - ipykernel
  - nbformat
  - nbclient
  - python=3.11
  - poincare
  - matplotlib
  - seaborn
  - tabulate
  - numba
  - pysb
  - tqdm
  - pytest
  - pydantic
  - lxml
  - rich
  - numbalsoda
  - pip
  - pip:
    - simbio[io]>=0.3.2
    - copasi-basico
    - tellurium
